site_name: My Docs

markdown_extensions:
  - meta
  - attr_list
  - toc:
      title: Table of Contents
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:  
  name: material
#  logo: assets/logo.png
#  favicon: images/favicon.png

  language: en
  font:
    text: Roboto
  palette:
    scheme: slate
    primary: yellow
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking

    

repo_url: https://github.com/squidfunk/mkdocs-material
repo_name: squidfunk/mkdocs-material

extra:
  generator: false
  homepage: https://example.com

copyright: Copyright &copy; 2016 - 2020 Martin Donath
